#ifndef OPCODE_LUT_H
#define OPCODE_LUT_H

#include <stdexcept>

#include <MOS6502/Instruction.h>
#include <MOS6502/Operation.h>
#include <MOS6502/AddressingMode.h>

class OpcodeLUT {

    friend class MOS6502; //only this class can create an OpcodeLUT object

private:

    Instruction& operator[](const size_t& code) { 
        if (code < 0 || 255 < code) {
            std::string errorMessage("Error: Opcode index out of range with value ");
            errorMessage += code;
            throw std::runtime_error(errorMessage);
        }
        return mOpcodes[code]; 
    }

    Instruction mOpcodes[256] = {
        Instruction("BRK", BRK::getInstance(), IMP::getInstance(), 7),
        Instruction("ORA indirect X", ORA::getInstance(), IDX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("ORA Zero Page", ORA::getInstance(), ZP0::getInstance(), 3),
        Instruction("ASL Zero Page", ASL::getInstance(), ZP0::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("PHP", PHP::getInstance(), IMP::getInstance(), 3),
        Instruction("ORA Immediate", ORA::getInstance(), IMM::getInstance(), 2),
        Instruction("ASL Accumulator", ASL::getInstance(), ACC::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("ORA Absolute", ORA::getInstance(), ABS::getInstance(), 4),
        Instruction("ASL Absolute", ASL::getInstance(), ABS::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BPL", BPL::getInstance(), REL::getInstance(), 2),
        Instruction("ORA (Indirect),Y", ORA::getInstance(), IDY::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("ORA Zero Page,X", ORA::getInstance(), ZPX::getInstance(), 4),
        Instruction("ASL Zero Page,X", ASL::getInstance(), ZPX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("CLC", CLC::getInstance(), IMP::getInstance(), 2),
        Instruction("ORA Absolute,Y", ORA::getInstance(), ABY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("ORA Absolute,X", ORA::getInstance(), ABX::getInstance(), 4),
        Instruction("ASL Absolute,X", ASL::getInstance(), ABS::getInstance(), 7),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("JSR Absolute", JSR::getInstance(), ABS::getInstance(), 6),
        Instruction("AND (Indirect,X)", AND::getInstance(), IDX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BIT Zero Page", BIT::getInstance(), ZP0::getInstance(), 3),
        Instruction("AND Zero Page", AND::getInstance(), ZP0::getInstance(), 3),
        Instruction("ROL Zero Page", ROL::getInstance(), ZP0::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("PLP", PLP::getInstance(), IMP::getInstance(), 4),
        Instruction("AND Immediate", AND::getInstance(), IMM::getInstance(), 2),
        Instruction("ROL Accumulator", ROL::getInstance(), ACC::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BIT Absolute", BIT::getInstance(), ABS::getInstance(), 4),
        Instruction("AND Absolute", AND::getInstance(), ABS::getInstance(), 4),
        Instruction("ROL Absolute", ROL::getInstance(), ABS::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BMI", BMI::getInstance(), REL::getInstance(), 2),
        Instruction("AND (Indirect),Y", AND::getInstance(), IDY::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("AND Zero Page,X", AND::getInstance(), ZP0::getInstance(), 3),
        Instruction("ROL Zero Page,X", ROL::getInstance(), ZPX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("SEC", SEC::getInstance(), IMP::getInstance(), 2),
        Instruction("AND Absolute,Y", AND::getInstance(), ABY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("AND Absolute,X", AND::getInstance(), ABX::getInstance(), 4),
        Instruction("ROL Absolute,X", ROL::getInstance(), ABX::getInstance(), 7),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("RTI", RTI::getInstance(), IMP::getInstance(), 6),
        Instruction("EOR (Indirect,X)", EOR::getInstance(), IDX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("EOR Zero Page", EOR::getInstance(), ZP0::getInstance(), 3),
        Instruction("LSR Zero Page", LSR::getInstance(), ZP0::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("PHA", PHA::getInstance(), IMP::getInstance(), 3),
        Instruction("EOR Immediate", EOR::getInstance(), IMM::getInstance(), 2),
        Instruction("LSR Accumulator", LSR::getInstance(), ACC::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("JMP Absolute", JMP::getInstance(), ABS::getInstance(), 3),
        Instruction("EOR Absolute", EOR::getInstance(), ABS::getInstance(), 4),
        Instruction("LSR Absolute", LSR::getInstance(), ABS::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BVC", BVC::getInstance(), REL::getInstance(), 2),
        Instruction("EOR (Indirect),Y", EOR::getInstance(), IDY::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("EOR Zero Page,X", EOR::getInstance(), ZPX::getInstance(), 4),
        Instruction("LSR Zero Page,X", LSR::getInstance(), ZPX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("CLI", CLI::getInstance(), IMP::getInstance(), 2),
        Instruction("EOR Absolute,Y", EOR::getInstance(), ABY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("EOR Absolute,X", EOR::getInstance(), ABX::getInstance(), 4),
        Instruction("LSR Absolute,X", LSR::getInstance(), ABX::getInstance(), 7),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("RTS", RTS::getInstance(), IMP::getInstance(), 6),
        Instruction("ADC (Indirect,X)", ADC::getInstance(), IDX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("ADC Zero Page", ADC::getInstance(), ZP0::getInstance(), 3),
        Instruction("ROR Zero Page", ROR::getInstance(), ZP0::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("PLA", PLA::getInstance(), IMP::getInstance(), 4),
        Instruction("ADC Immediate", ADC::getInstance(), IMM::getInstance(), 2),
        Instruction("ROR Accumulator", ROR::getInstance(), ACC::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("JMP (Indirect)", JMP::getInstance(), IND::getInstance(), 5),
        Instruction("ADC Absolute", ADC::getInstance(), ABS::getInstance(), 4),
        Instruction("ROR Absolute", ROR::getInstance(), ABS::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BVS", BVS::getInstance(), REL::getInstance(), 2),
        Instruction("ADC (Indirect),Y", ADC::getInstance(), IDY::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("ADC Zero Page,X", ADC::getInstance(), ZPX::getInstance(), 4),
        Instruction("ROR Zero Page,X", ROR::getInstance(), ZPX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("SEI", SEI::getInstance(), IMP::getInstance(), 2),
        Instruction("ADC Absolute,Y", ADC::getInstance(), ABY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("ADC Absolute,X", ADC::getInstance(), ABX::getInstance(), 4),
        Instruction("ROR Absolute,X", ROR::getInstance(), ABX::getInstance(), 7),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("STA (Indirect,X)", STA::getInstance(), IDX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("STY Zero Page", STY::getInstance(), ZP0::getInstance(), 3),
        Instruction("STA Zero Page", STA::getInstance(), ZP0::getInstance(), 3),
        Instruction("STX Zero Page", STX::getInstance(), ZP0::getInstance(), 3),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("DEY", DEY::getInstance(), IMP::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("TXA", TXA::getInstance(), IMP::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("STY Absolute", STY::getInstance(), ABS::getInstance(), 4),
        Instruction("STA Absolute", STA::getInstance(), ABS::getInstance(), 4),
        Instruction("STX Absolute", STX::getInstance(), ABS::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BCC", BCC::getInstance(), REL::getInstance(), 2),
        Instruction("STA (Indirect),Y", STA::getInstance(), IDY::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("STY Zero Page,X", STY::getInstance(), ZPX::getInstance(), 4),
        Instruction("STA Zero Page,X", STA::getInstance(), ZPX::getInstance(), 4),
        Instruction("STX Zero Page,Y", STX::getInstance(), ZPY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("TYA", TYA::getInstance(), IMP::getInstance(), 2),
        Instruction("STA Absolute,Y", STA::getInstance(), ABY::getInstance(), 5),
        Instruction("TXS", TXS::getInstance(), IMP::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("STA Absolute,X", STA::getInstance(), ABX::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("LDY Immediate", LDY::getInstance(), IMM::getInstance(), 2),
        Instruction("LDA (Indirect,X)", LDA::getInstance(), IDX::getInstance(), 6),
        Instruction("LDX Immediate", LDX::getInstance(), IMM::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("LDY Zero Page", LDY::getInstance(), ZP0::getInstance(), 3),
        Instruction("LDA Zero Page", LDA::getInstance(), ZP0::getInstance(), 3),
        Instruction("LDX Zero Page", LDX::getInstance(), ZP0::getInstance(), 3),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("TAY", TAY::getInstance(), IMP::getInstance(), 2),
        Instruction("LDA Immediate", LDA::getInstance(), IMM::getInstance(), 2),
        Instruction("TAX", TAX::getInstance(), IMP::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("LDY Absolute", LDY::getInstance(), ABS::getInstance(), 4),
        Instruction("LDA Absolute", LDA::getInstance(), ABS::getInstance(), 4),
        Instruction("LDX Absolute", LDX::getInstance(), ABS::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BCS", BCS::getInstance(), REL::getInstance(), 2),
        Instruction("LDA (Indirect),Y", LDA::getInstance(), IDY::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("LDY Zero Page,X", LDY::getInstance(), ZPX::getInstance(), 4),
        Instruction("LDA Zero Page,X", LDA::getInstance(), ZPX::getInstance(), 4),
        Instruction("LDX Zero Page,Y", LDX::getInstance(), ZPY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("CLV", CLV::getInstance(), IMP::getInstance(), 2),
        Instruction("LDA Absolute,Y", LDA::getInstance(), ABY::getInstance(), 4),
        Instruction("TSX", TSX::getInstance(), IMP::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("LDY Absolute,X", LDY::getInstance(), ABX::getInstance(), 4),
        Instruction("LDA Absolute,X", LDA::getInstance(), ABX::getInstance(), 4),
        Instruction("LDX Absolute,Y", LDX::getInstance(), ABY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("CPY Immediate", CPY::getInstance(), IMM::getInstance(), 2),
        Instruction("CMP (Indirect,X)", CMP::getInstance(), IDX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("CPY Zero Page", CPY::getInstance(), ZP0::getInstance(), 3),
        Instruction("CMP Zero Page", CMP::getInstance(), ZP0::getInstance(), 3),
        Instruction("DEC Zero Page", DEC::getInstance(), ZP0::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("INY", INY::getInstance(), IMP::getInstance(), 2),
        Instruction("CMP Immediate", CMP::getInstance(), IMM::getInstance(), 2),
        Instruction("DEX", DEX::getInstance(), IMP::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("CPY Absolute", CPY::getInstance(), ABS::getInstance(), 4),
        Instruction("CMP Absolute", CMP::getInstance(), ABS::getInstance(), 4),
        Instruction("DEC Absolute", DEC::getInstance(), ABS::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BNE", BNE::getInstance(), REL::getInstance(), 2),
        Instruction("CMP (Indirect),Y", CMP::getInstance(), IDY::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("CMP Zero Page X", CMP::getInstance(), ZPX::getInstance(), 4),
        Instruction("DEC Zero Page,X", DEC::getInstance(), ZPX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("CLD", CLD::getInstance(), IMP::getInstance(), 2),
        Instruction("CMP Absolute,Y", CMP::getInstance(), ABY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("CMP Absolute,X", CMP::getInstance(), ABX::getInstance(), 4),
        Instruction("DEC Absolute,X", DEC::getInstance(), ABX::getInstance(), 7),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("CPX Immediate", CPX::getInstance(), IMM::getInstance(), 2),
        Instruction("SBC (Indirect,X)", SBC::getInstance(), IDX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("CPX Zero Page", CPX::getInstance(), ZP0::getInstance(), 3),
        Instruction("SBC Zero Page", SBC::getInstance(), ZP0::getInstance(), 3),
        Instruction("INC Zero Page", INC::getInstance(), ZP0::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("INX", INX::getInstance(), IMP::getInstance(), 2),
        Instruction("SBC Immediate", SBC::getInstance(), IMM::getInstance(), 2),
        Instruction("NOP", NOP::getInstance(), IMP::getInstance(), 2),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("CPX Absolute", CPX::getInstance(), ABS::getInstance(), 4),
        Instruction("SBC Absolute", SBC::getInstance(), ABS::getInstance(), 4),
        Instruction("INC Absolute", INC::getInstance(), ABS::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("BEQ", BEQ::getInstance(), REL::getInstance(), 2),
        Instruction("SBC (Indirect),Y", SBC::getInstance(), IDY::getInstance(), 5),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("SBC Zero Page,X", SBC::getInstance(), ZPX::getInstance(), 4),
        Instruction("INC Zero Page,X", INC::getInstance(), ZPX::getInstance(), 6),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("SED", SED::getInstance(), IMP::getInstance(), 2),
        Instruction("SBC Absolute,Y", SBC::getInstance(), ABY::getInstance(), 4),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0), 
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0),
        Instruction("SBC Absolute,X", SBC::getInstance(), ABX::getInstance(), 4),
        Instruction("INC Absolute,X", INC::getInstance(), ABX::getInstance(), 7),
        Instruction("Undefined", UndefinedOperation::getInstance(), UndefinedAddressingMode::getInstance(), 0)
    };

};

#endif // !OPCODE_LUT_H
